server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team_matching
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# application.yml 예시 (테스트용으로 사용 가능한 512bit 이상의 Base64 문자열)
jwt:
  secret: c3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1rZXktc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1rZXk=
  access-token-validity-in-seconds: 86400